### ISSUE TITLE
nice idea!

### ISSUE THREAD

**Issue by enaros** [trusktr/rocket-module#3]
great job man, looking forward to see how this project evolves!

**Comment by sarendipitee** [comment]
Yea this is beautiful! My biggest gripe with Meteor is the disgusting initial payload that can be multi-megabytes, but Meteor Core devs don't seem to give a shit about **the** most important part about web development: load times. I can't wait to try this out on a new project and get some delicious webpack code-splitting.

**Comment by trusktr** [comment]
@enaros @JonDum  Thanks guys! I'm working hard on it right now. I want to release as soon as possible!

**Comment by trusktr** [comment]
I'm aiming for before June is over, hopefully there's no roadblocks to hurdle.

**Comment by trusktr** [comment]
Aah, two days until the end of June. It might not happen. I'll be hacking on this today. :D
