### ISSUE TITLE
TypeScript Support?

### ISSUE THREAD

**Issue by Gaelan** [trusktr/rocket-module#6]
How hard would it be to add TypeScript as an additional option alongside Babel (I'm presuming that is what you are using)?

**Comment by trusktr** [comment]
@Gaelan Hello, sorry for such a late reply. `rocket:module` is deprecated in favor of Meteor 1.3's `modules` system. There's also an active package, webpack:webpack, that has more or less taken the role of what rocket:module was doing. https://atmospherejs.com/webpack/webpack

webpack:webpack already supports configuring Babel, and Meteor 1.3 is aiming to have support for that as well, before 1.4.

**Comment by trusktr** [comment]
There's `.babelrc` support in Meteor nowadays!
