### ISSUE TITLE
Babel issues

### ISSUE THREAD

**Issue by barbatus** [trusktr/rocket-module#8]
When I use this package to compile jsx files, I get "'import' and 'export' may only
 appear at the top level" exception while Meteor's Babel works fine at the same time.
Also, do you have plans to expend rocket-module.json to configure Babel-loader as well?
It'd be useful to set, for example, system or decorator configuration options of Babel.

**Comment by adamwong246** [comment]
+1

**Comment by trusktr** [comment]
Hey guys, sorry I never responded. I sort of abandoned this in favor of Meteor 1.3+ `modules`. Plus now Meteor has `.babelrc` config!
